spring:
  application:
    name: store
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: meow
    password: meowpwd
  jpa:
    show-sql: true
