spring:
  application:
    name: store
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2h
    refreshTokenExpiration: 2_592_000 # 30 days

logging:
  level:
    root: INFO
    com.ken.store: DEBUG 
    org.hibernate.SQL: DEBUG 
  file:
    name: logs/app.log 

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:8080/payment-result